backend:
  image: python:3.10-slim
  working_dir: /app
  volumes:
    - ./backend:/app
  command: sh -c "pip install -r requirements.txt && python app.py"
  ports:
    - "5000:5000"
  depends_on:
    - db

